language: node_js
node_js: 
  - stable
script:
  - npm install
  - npm run build
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: dist
  on:
    branch: master